### ISSUE TITLE
After selecting residue, no rotation of the protein possible

### ISSUE THREAD

**Issue by funkefel** [helenginn/mabscape#4]
This may be caused by alt-tabbing out of the window and back in again.
Also happend after refining the mesh.

**Comment by helenginn** [comment]
This sounds like a Qt::setFocus, Qt::setFocusPolicy or similar issue, taking focus away from the SurfaceView but not returning it

**Comment by funkefel** [comment]
ec14c33
The _gl needed to accept Focus of the window in order to be able to rotate the structure again.

**Comment by funkefel** [comment]
af3b961
Previous fix destroyed the ability to highlight or select antibodies, which was a cause of the SlipGL accepting focus.
The issue that broke rotation was, that upon exiting the window with Alt+Tab, the variable _controllPressed was constantly set to true, which disabled most of the hovering commands and rotation of the protein. This could be resolved by pressing the Alt key.
Now the programm automatically sets the _controllPressed to false, when it regains focus.
